name: 'Sync Github Projects to Jira'
description: 'Sync Github Projects to Jira'
runs:
  using: 'node20'
  main: 'lib/index.js'
inputs:
  jiraHost:
    description: 'URL of the Jira instance'
    required: true
  jiraWriteToken:
    description: 'Jira REST API token with write access'
    required: true
  githubReadToken:
    description: 'GitHub token with read access to the repositories to sync'
    required: true
