name: 'Sync Github Projects to Jira'
description: 'Sync Github Projects to Jira'
runs:
  using: 'node20'
  main: 'lib/index.mjs'
inputs:
  jira-host:
    description: 'URL of the Jira instance'
    required: true
  jira-write-token:
    description: 'Jira REST API token with write access'
    required: true
  github-read-token:
    description: 'GitHub token with read access to the repositories to sync'
    required: true
